spring.datasource.url=jdbc:postgresql://localhost:5432/cloud_storage_db
spring.datasource.username=postgres
spring.datasource.password=Kaus@804422
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080